kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: azure-disk-storageclass-reader-resizer-binding
subjects:
  - kind: ServiceAccount
    name: azure-disk-csi-driver-controller-sa
    namespace: openshift-cluster-csi-drivers
roleRef:
  kind: ClusterRole
  name: openshift-csi-resizer-storageclass-reader-role
  apiGroup: rbac.authorization.k8s.io
